services:
  postgres:
    image: postgres:15
    container_name: urfu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8800
      POSTGRES_DB: urfu_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - postgres
    environment:
      # Подключаемся к postgres по имени сервиса
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=urfu_db;Username=postgres;Password=8800"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"   # HTTP-порт API

  webapp:
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - api
    environment:
      # Внутри Docker-сети WebApp дозванивается до API по этому адресу
      Api__BaseUrl: "http://api:80"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8081"   # HTTP-порт фронтенда

volumes:
  pgdata:
